### ISSUE TITLE
View previous commands in bb shell using up arrow

### ISSUE THREAD

**Issue by naclander** [borkdude/babashka#257]
**Is your feature request related to a problem? Please describe.**
When using the repl, I want to bring up previous commands and edit them. In bash this is usually done with the `up/down` arrows, but in `babashka` I only get `^[[A`

**Describe the solution you'd like**
When pressing `up` or `down`, the shell should cycle through the command history.

**Describe alternatives you've considered**
Using `Ctr+p` in addition to `up`. Using my mouse like an animal to copy and paste my previous commands.

**Additional context**
Thanks for helping me incorporate clojure into my bash!

**Comment by borkdude** [comment]
Hi @naclander. You're better of using `rlwrap` in combination with the `bb` repl. This is also what the standard `clojure` tooling uses.

**Comment by borkdude** [comment]
@naclander I now added a note about this in the README:

https://github.com/borkdude/babashka/commit/01714e4bbb840dbbe5d1b5adb586256604e6157a

I hope this fixes your issue. If not, feel free to report back.

**Comment by thiagokokada** [comment]
@borkdude For user friendliness, could you consider wrapping automatically the REPL if `rlwrap` is installed in the user system (and showing a warning saying that history is not available in case it is not to?).

I was bitten quite a feel times by this problem until I found this issue here and I was even avoiding Babashka's REPL because of this. The note in REPL is not really helpful since I didn't know what `rlwrap` means.

Well, of course this is just a suggestion. Like I said before, this is a great project!

**Comment by smithtim** [comment]
Would it be possible to just build this functionality into `bb repl`?  To have to type `rlwrap bb repl` is not so convenient, and my system does not even have `rlwrap`.

P.S. Thanks for your work on babashka, it's great!
