### ISSUE TITLE
Add prepl support

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#330]
See https://nrepl.org/nrepl/0.7.0/alternatives.html#_prepl.

Maybe @olical has some input on this.

**Comment by borkdude** [comment]
Summary of discussion about pREPL vs nREPL:

```
1) prepl is not consistently implemented across clojure and cljs
2) it has bugs for which Olical filed issues, but as might be expected they aren't being addressed particularly quickly
3) in his opinion it's more suited to program to program communication
4) he's had extensive experience with prepl and has decided that though he won't drop support for it, he is working to incorporate nrepl after his experience
```

**Comment by borkdude** [comment]
https://oli.me.uk/clojure-prepl-for-tool-authors/
https://oli.me.uk/clojure-socket-prepl-cookbook/
https://oli.me.uk/repling-into-projects-with-prepl-and-propel/
https://oli.me.uk/exploring-repl-tooling-with-prepl/

**Comment by borkdude** [comment]
I'll not work on it unless someone shows interest. Closing until then.

**Comment by bbatsov** [comment]
Thanks for sharing the extra insight from @Olical! I wasn't aware that the implementation differed between Clojure and ClojureScript. I might add some of this to nREPL's docs, as my exposure to prepl was pretty limited.

**Comment by Olical** [comment]
Yep, they're all thin wrappers around a regular socket REPL. Since the implementation is small there's no code reuse, which means inconsistencies. You get reader conditionals in one but not the other is a fun one. Clojure default is different from ClojureScript default is different from Shadow is different from [any tool that implements a prepl server].

Clojure tells you when a result is an exception, ClojureScript does not.

ClojureScript used to return results as actual EDN data within the response rather than a string of the result. This caused a the Rust EDN parser to choke on a bunch of things for me. I've submitted patches for almost all of the issues, but there's still no access to the CLJS REPL env or state.

So even though Clojure kind of works okay (no interrupt unless you implement it and no reader conditionals so you need to write your own eval wrapper), the ClojureScript side is SUPER limited, would require substantial changes.

I could write a better prepl server for Clojure and ClojureScript, but adding a dep for a thing that's supposed to be built in feels kind of silly. So far I'm very happy with just jumping onto the wonders of the nREPL boat, it solved so many problems right away.

prepl is cool, I like the idea, it just needs a standard implementation and a lot more thought if it's to be used as the basis for smarter tools. Implementing prepl in your other thing should be a library you import that forces you down the right and consistent path right away. Not a vague "oh it sort of works like this, good like implementing it yourself" :grimacing:

**Comment by bbatsov** [comment]
That's super useful info! Thanks for sharing it!

> I could write a better prepl server for Clojure and ClojureScript, but adding a dep for a thing that's supposed to be built in feels kind of silly. So far I'm very happy with just jumping onto the wonders of the nREPL boat, it solved so many problems right away.

Glad to hear this! I guess this is a nice validation of our theory we did something right! 😄
